### PR TITLE
Support initial data in C-set homomorphism search

### LINKED ISSUE #435: Partial homomorphism assignment as input
Often, a homomorphism is fully determined by some subset of the data required to specify  it. It would be helpful to constrain the output of `homomorphisms` by a starting partial assignment.

One potential interface could involve giving a list of pairs  for some subset of the components, e.g.
```julia
homomorphisms(Graph1, Graph2, monic=true, V=[1 => 2, 4 => 3], E=[2 => 1])
```

### PR DESCRIPTION
**Pull request by epatters**
Closes #435.

### CODE REVIEW

**Comment by epatters** [comment]
@mehalter, the review checklist is failing. Sigh, I thought we fixed that.

**Comment by mehalter** [comment]
@epatters this is a strange error I haven't seen before with the action. The GitHub API is returning 403 Forbidden. Initial thoughts is it's a bug with the GitHub Octokit or a part of the API might be down. Will investigate today

**Comment by epatters** [comment]
@mehalter, after #439, the review checklist action is still failing but with a different error message. Note that I rebased off master so that shouldn't be the problem.

**Review by kris-brown — APPROVED** [review]
This looks great!

**Pull request merged**
