### PR TITLE
Bundle legs of structured multicospans

### PR DESCRIPTION
**Pull request by epatters**
Adds a function `bundle_legs` that combines the legs of multispans, multicospans, or structured multicospans using (co)products.

### CODE REVIEW

**Review by mehalter — APPROVED** [review]
This is great, can't wait to give this a try in AlgebraicPetri

**Comment by mehalter** [comment]
Just tested this branch with AlgPetri and the COEXIST model and it's working perfectly!

**Review by bosonbaas — APPROVED** [review]
This is exactly what I was looking for, thanks! I've gotten it running with dynamical systems.

**Comment by epatters** [comment]
Great, glad this seems to be working well!

**Pull request merged**
