### PR TITLE
Add Literate graphs/graphs.jl

### PR DESCRIPTION
**Pull request by jpfairbanks**
Here are some introductory docs about CSets with the example of graphs.

### CODE REVIEW

**Comment by jpfairbanks** [comment]
@epatters @mehalter, I think i messed up a pull/push with rebase on this one

**Comment by jpfairbanks** [comment]
The commits I actually want are 8f7e5cf and 10dd970

**Comment by epatters** [comment]
The easiest thing to do is create a new branch off Catlab master, cherry pick those two commits, and make a new PR. Or, easier still, create a new branch, copy-paste your file, and add a single commit.

**Comment by epatters** [comment]
Thanks for the docs!

**Pull request closed without merging**
