### PR TITLE
Use Graphviz_jll instead of relying on local installation

### PR DESCRIPTION
**Pull request by christopher-dG**
Needs https://github.com/JuliaPackaging/Yggdrasil/pull/1413

I just went by what @isaacsas said in https://github.com/SciML/Catalyst.jl/issues/237#issuecomment-669335772, if there are other changes required let me know.

I'm not sure if there's a compat entry I can add to Graphviz_jll since I don't think compat works with build numbers.
Also important to note is that using a JLL package requires Julia 1.3+, alternatively we could do a version check in the code and expect a manual installation if we're on < 1.3.

### CODE REVIEW

**Comment by epatters** [comment]
Thanks a lot for putting this together so quickly.

With some prodding from @mehalter, I just restored Catlab's compatibility with Julia 1.0 (#227), which I'd like to preserve. So let's have a conditional import and just expect that Graphviz be manually installed on Julia < v1.3. That new LTS can't come soon enough!

**Comment by mehalter** [comment]
Yeah I agree, this is a great addition and will be nice once we don't have to rely on v1.0! Great place to do a conditional import here and get it in v1.3+ installations

**Comment by christopher-dG** [comment]
Hm, 1.0 failure is a compat constraint issue, I suck at reading these:

```
ERROR: Unsatisfiable requirements detected for package Pango_jll [36c8627f]:
 Pango_jll [36c8627f] log:
 ├─possible versions are: 1.42.4 or uninstalled
 ├─restricted by julia compatibility requirements to versions: uninstalled
 └─restricted by compatibility requirements with Graphviz_jll [3c863552] to versions: 1.42.4 — no versions left
   └─Graphviz_jll [3c863552] log:
     ├─possible versions are: 2.42.3 or uninstalled
     └─restricted to versions * by Catlab [134e5e36], leaving only versions 2.42.3
       └─Catlab [134e5e36] log:
         ├─possible versions are: 0.7.3 or uninstalled
         └─Catlab [134e5e36] is fixed to version 0.7.3
```

**Comment by epatters** [comment]
Looks like it's trying and failing to install the Graphviz_jll package on Julia 1.0 because it's in the Project.toml. Not immediately clear how to prevent this. Does anybody know?

**Comment by christopher-dG** [comment]
It's fine to install a JLL on older versions, just not to load them. At least that's how they're supposed to be.

**Comment by giordano** [comment]
Pango_jll has a wrong compat bound (it's very old), https://github.com/JuliaRegistries/General/blob/master/P/Pango_jll/Compat.toml#L2 this should be 1. Mind opening a pull request?

**Comment by epatters** [comment]
Looks like Expat_jll has the same problem. PR filed. The quest continues.

**Comment by christopher-dG** [comment]
There are a lot of JLLs with this problem, it would appear. I'm guessing some of them are legit, but definitely not all. @giordano thoughts on what should be done?

```
$ grep 'julia = "1\.' */*_jll/Compat.toml

A/adwaita_icon_theme_jll/Compat.toml:julia = "1.3.0-1"
A/alsa_jll/Compat.toml:julia = "1.3.0-1"
A/Arpack_jll/Compat.toml:julia = "1.3.0-1"
A/ASL_jll/Compat.toml:julia = "1.3.0-1"
A/ATK_jll/Compat.toml:julia = "1.3.0-1"
A/at_spi2_atk_jll/Compat.toml:julia = "1.3.0-1"
A/at_spi2_core_jll/Compat.toml:julia = "1.3.0-1"
A/Attr_jll/Compat.toml:julia = "1.3.0-1"
B/boost_jll/Compat.toml:julia = "1.3.0-1"
B/Bzip2_jll/Compat.toml:julia = "1.3.0-1"
C/CFITSIO_jll/Compat.toml:julia = "1.3.0-1"
C/CompilerSupportLibraries_jll/Compat.toml:julia = "1.3.0-1"
D/Darknet_jll/Compat.toml:julia = "1.3.0-1"
D/Dbus_jll/Compat.toml:julia = "1.3.0-1"
E/Elfutils_jll/Compat.toml:julia = "1.3.0-1"
F/FastTransforms_jll/Compat.toml:julia = "1.3.0-1"
F/FFMPEG_jll/Compat.toml:julia = "1.3.0-1"
F/FFTW_jll/Compat.toml:julia = "1.3.0-1"
F/FLAC_jll/Compat.toml:julia = "1.3.0-1"
F/Fontconfig_jll/Compat.toml:julia = "1.3.0-1"
F/FreeType2_jll/Compat.toml:julia = "1.3.0-1"
F/FriBidi_jll/Compat.toml:julia = "1.3.0-1"
G/gdk_pixbuf_jll/Compat.toml:julia = "1.3.0-1"
G/GEOS_jll/Compat.toml:julia = "1.3.0-1"
G/Gettext_jll/Compat.toml:julia = "1.3.0-1"
G/ghr_jll/Compat.toml:julia = "1.3.0-1"
G/GibbsSeaWater_jll/Compat.toml:julia = "1.3.0-1"
G/Giflib_jll/Compat.toml:julia = "1.3.0-1"
G/Git_jll/Compat.toml:julia = "1.3.0-1"
G/GLEW_jll/Compat.toml:julia = "1.3.0-1"
G/GLFW_jll/Compat.toml:julia = "1.3.0-1"
G/Glib_jll/Compat.toml:julia = "1.3.0-1"
G/GMP_jll/Compat.toml:julia = "1.6"
G/Gnome_themes_extra_jll/Compat.toml:julia = "1.3.0-1"
G/Graphene_jll/Compat.toml:julia = "1.3.0-1"
G/Graphite2_jll/Compat.toml:julia = "1.3.0-1"
G/GSL_jll/Compat.toml:julia = "1.3.0-1"
G/GTK3_jll/Compat.toml:julia = "1.3.0-1"
H/HarfBuzz_jll/Compat.toml:julia = "1.3.0-1"
H/HDF5_jll/Compat.toml:julia = "1.3.0-1"
H/HelloWorldC_jll/Compat.toml:julia = "1.3.0-1"
H/hicolor_icon_theme_jll/Compat.toml:julia = "1.3.0-1"
I/ImageMagick_jll/Compat.toml:julia = "1.3.0-1"
I/iso_codes_jll/Compat.toml:julia = "1.3.0-1"
J/JpegTurbo_jll/Compat.toml:julia = "1.3.0-1"
K/Keyutils_jll/Compat.toml:julia = "1.3.0-1"
L/LAME_jll/Compat.toml:julia = "1.3.0-1"
L/libass_jll/Compat.toml:julia = "1.3.0-1"
L/libcap_jll/Compat.toml:julia = "1.3.0-1"
L/Libcap_Ng_jll/Compat.toml:julia = "1.3.0-1"
L/Libcroco_jll/Compat.toml:julia = "1.3.0-1"
L/LibCURL_jll/Compat.toml:julia = "1.3.0-1"
L/Libepoxy_jll/Compat.toml:julia = "1.3.0-1"
L/libfdk_aac_jll/Compat.toml:julia = "1.3.0-1"
L/Libffi_jll/Compat.toml:julia = "1.3.0-1"
L/Libgcrypt_jll/Compat.toml:julia = "1.3.0-1"
L/LibGit2_jll/Compat.toml:julia = "1.3.0-1"
L/LibGit2_jll/Compat.toml:julia = "1.7"
L/Libglvnd_jll/Compat.toml:julia = "1.3.0-1"
L/Libgpg_error_jll/Compat.toml:julia = "1.3.0-1"
L/libLLVM_jll/Compat.toml:julia = "1.4"
L/libLLVM_jll/Compat.toml:julia = "1.5-1.6"
L/libLLVM_jll/Compat.toml:julia = "1.7"
L/libmodplug_jll/Compat.toml:julia = "1.3.0-1"
L/Libmount_jll/Compat.toml:julia = "1.3.0-1"
L/libpng_jll/Compat.toml:julia = "1.3.0-1"
L/libportaudio_jll/Compat.toml:julia = "1.3.0-1"
L/Librsvg_jll/Compat.toml:julia = "1.3.0-1"
L/libserialport_jll/Compat.toml:julia = "1.3.0-1"
L/libsndfile_jll/Compat.toml:julia = "1.3.0-1"
L/Libtiff_jll/Compat.toml:julia = "1.3.0-1"
L/LibUnwind_jll/Compat.toml:julia = "1.3.0-1"
L/Libuuid_jll/Compat.toml:julia = "1.3.0-1"
L/LibUV_jll/Compat.toml:julia = "1.3.0-1"
L/libvorbis_jll/Compat.toml:julia = "1.3.0-1"
L/LibVPX_jll/Compat.toml:julia = "1.3.0-1"
L/libwebp_jll/Compat.toml:julia = "1.3.0-1"
L/LLVM_jll/Compat.toml:julia = "1.0-1.3"
L/LLVM_jll/Compat.toml:julia = "1.4"
L/lm_Sensors_jll/Compat.toml:julia = "1.3.0-1"
L/Lua_jll/Compat.toml:julia = "1.3.0-1"
L/Lz4_jll/Compat.toml:julia = "1.3.0-1"
L/LZO_jll/Compat.toml:julia = "1.3.0-1"
M/Mineos_jll/Compat.toml:julia = "1.3.0-1"
M/MKL_jll/Compat.toml:julia = "1.3.0-1"
M/MPFR_jll/Compat.toml:julia = "1.7"
M/mpg123_jll/Compat.toml:julia = "1.3.0-1"
N/Ncurses_jll/Compat.toml:julia = "1.3.0-1"
N/Nettle_jll/Compat.toml:julia = "1.3.0-1"
O/Ogg_jll/Compat.toml:julia = "1.3.0-1"
O/OpenBLAS_jll/Compat.toml:julia = "1.3.0-1"
O/OpenSpecFun_jll/Compat.toml:julia = "1.3.0-1"
O/OptimPack_jll/Compat.toml:julia = "1.3.0-1"
O/Opus_jll/Compat.toml:julia = "1.3.0-1"
P/p7zip_jll/Compat.toml:julia = "1.3.0-1"
P/Patchelf_jll/Compat.toml:julia = "1.3.0-1"
P/PATHlib_jll/Compat.toml:julia = "1.3.0-1"
P/PCRE2_jll/Compat.toml:julia = "1.3.0-1"
P/PCRE_jll/Compat.toml:julia = "1.3.0-1"
P/Pixman_jll/Compat.toml:julia = "1.3.0-1"
Q/Qemu_jll/Compat.toml:julia = "1.3.0-1"
R/Readline_jll/Compat.toml:julia = "1.3.0-1"
R/ReadStat_jll/Compat.toml:julia = "1.3.0-1"
R/Rmath_jll/Compat.toml:julia = "1.3.0-1"
S/SDL2_jll/Compat.toml:julia = "1.3.0-1"
S/SharedMimeInfo_jll/Compat.toml:julia = "1.3.0-1"
S/SoftPosit_jll/Compat.toml:julia = "1.3.0-1"
S/spglib_jll/Compat.toml:julia = "1.3.0-1"
S/SPIRV_LLVM_Translator_jll/Compat.toml:julia = "1.4"
S/SPIRV_LLVM_Translator_jll/Compat.toml:julia = "1.5-1.6"
S/SPIRV_LLVM_Translator_jll/Compat.toml:julia = "1.7"
S/SQLite_jll/Compat.toml:julia = "1.3.0-1"
T/Tcl_jll/Compat.toml:julia = "1.3.0-1"
T/Tk_jll/Compat.toml:julia = "1.3.0-1"
T/TVM_jll/Compat.toml:julia = "1.3.0-1"
W/Wayland_jll/Compat.toml:julia = "1.3.0-1"
W/Wayland_protocols_jll/Compat.toml:julia = "1.3.0-1"
W/WCS_jll/Compat.toml:julia = "1.3.0-1"
X/X11_jll/Compat.toml:julia = "1.3.0-1"
X/x264_jll/Compat.toml:julia = "1.3.0-1"
X/x265_jll/Compat.toml:julia = "1.3.0-1"
X/xhyve_jll/Compat.toml:julia = "1.3.0-1"
X/xkbcommon_jll/Compat.toml:julia = "1.3.0-1"
X/XML2_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_compositeproto_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_damageproto_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_dri2proto_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_dri3proto_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_fixesproto_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_glproto_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_inputproto_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_kbproto_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_libpthread_stubs_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_libX11_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_libXau_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_libxcb_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_libXcomposite_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_libXcursor_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_libXdamage_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_libXdmcp_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_libXext_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_libXfixes_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_libXft_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_libXi_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_libXinerama_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_libxkbfile_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_libXrandr_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_libXrender_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_libXScrnSaver_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_libxshmfence_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_libXtst_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_libXxf86vm_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_randrproto_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_recordproto_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_renderproto_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_scrnsaverproto_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_util_macros_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_xcb_proto_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_xcb_util_image_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_xcb_util_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_xcb_util_keysyms_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_xcb_util_renderutil_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_xcb_util_wm_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_xextproto_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_xf86vidmodeproto_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_xineramaproto_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_xkbcomp_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_xkeyboard_config_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_xproto_jll/Compat.toml:julia = "1.3.0-1"
X/Xorg_xtrans_jll/Compat.toml:julia = "1.3.0-1"
X/XSLT_jll/Compat.toml:julia = "1.3.0-1"
X/XZ_jll/Compat.toml:julia = "1.3.0-1"
Z/z3_jll/Compat.toml:julia = "1.3.0-1"
Z/ZeroMQ_jll/Compat.toml:julia = "1.3.0-1"
Z/Zstd_jll/Compat.toml:julia = "1.3.0-1"
```

**Comment by giordano** [comment]
All those with `"1.3.0-1"` should likely be `"1"`, the others should very likely stay as they are

**Comment by christopher-dG** [comment]
Cool, only one more job to fix. Ironically that might be the only one that is actually using the changed code.

**Comment by christopher-dG** [comment]
It seems that there are no output formats available to the JLL binary:

```
$ ./dot -V
dot - graphviz version 2.42.3 (20191010.1750)

$ ./dot -Tfoo
Format: "foo" not recognized. Use one of:
```

When I run the same with a local Graphviz install:

```
$ dot -V
dot - graphviz version 2.44.1 (0)

$ dot -Tfoo
Format: "foo" not recognized. Use one of: bmp canon cmap cmapx cmapx_np dot dot_json eps fig gd gd2 gif gtk gv ico imap imap_np ismap jpe jpeg jpg json json0 mp pdf pic plain plain-ext png pov ps ps2 svg svgz tif tiff tk vdx vml vmlz vrml wbmp webp x11 xdot xdot1.2 xdot1.4 xdot_json xlib
```

**Comment by giordano** [comment]
You might need to figure out how to find them, see https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/687

**Comment by christopher-dG** [comment]
Turns out this is the cause: https://bugs.launchpad.net/ubuntu/+source/graphviz/+bug/1289063

I'm adding `dot -c` to the end of the build script and I think that should do it.

**Comment by epatters** [comment]
> Cool, only one more job to fix. Ironically that might be the only one that is actually using the changed code.

That's right, only the docs actually invoke Graphviz (as opposed to generating Graphviz AST). In general, the docs play an important role as "visual tests" for the graphics functionality.

Anyway, progress! Thanks @christopher-dG and @giordano for your help.

**Comment by epatters** [comment]
Great to see all the tests passing.

If I understand the meaning of `__init__` correctly, this call to `dot` will be made not at compile time but at run time, every time the module is loaded in a fresh Julia session. But doesn't this special call to `dot` only need to be called *once* during the lifetime of the `Graphviz_jll` package?

Also, do you know where this config file is generated? I wouldn't want Catlab to be responsible for generating a config file in an inappropriate place.

**Comment by christopher-dG** [comment]
Ah yes you're right, I'll fix up the init in the morning. The file is located relative to the artifact directory so it won't be noticeable to the user.

**Comment by mehalter** [comment]
This is some really cool work, great job to everyone going through so many hoops and fixing so many packages!

I have been playing around with this this morning and noticed that the size of the artifacts needed to just add `Graphviz_jll` is ≈283M. What if we used [Requires.jl](https://github.com/JuliaPackaging/Requires.jl) to make the dependency optional. If the user has `Graphviz_jll` on their system, use that instead of a system installation, but otherwise assume that `graphviz` is installed locally. This would allow for us to support users with different systems set up the way they prefer while also keeping our total install size low (23M without `graphviz_jll` vs 329M with)

**Comment by isaacsas** [comment]
Maybe flip that suggestion? i.e. detect if the user has an existing Graphviz install, and in that case `Graphviz_jll` isn't added? That seems more friendly to less advanced users / requires less of users, while those who want to custom set up Graphviz could avoid the jll. It would also make Catlab self-contained, which is useful for CI testing (otherwise users have to modify their packages that use Catlab to add the jll too).

**Comment by christopher-dG** [comment]
I don't think you can go the other way around, i.e. you can't dynamically remove a dependency (the JLL in this case).

**Comment by isaacsas** [comment]
Ahh, that's too bad.

**Comment by mehalter** [comment]
I mean make the package `Graphviz_jll` an optional dependency, and in the Graphviz set up have `Requires.jl` check to see if `Graphviz_jll` is installed and if it is, use it and run the `-c` to set up the config stuff. So if you just do `using Catlab` it doesn't add `Graphviz_jll` automatically.

**Comment by epatters** [comment]
Ideally, we would have Catlab automatically load Graphviz_jll whenever it is installed; however that is not possible AFAIK. So as a compromise I would suggest basically what @mehalter said:

- Make Graphviz_jll an [extra](https://github.com/AlgebraicJulia/Catlab.jl/blob/1c09a97c03d8466a27fd2adf7fc79f4ae5f82e7f/Project.toml#L49) dependency of Catlab
- Use Requires.jl to ensure that Catlab uses Graphviz_jll *if* it is has been imported. Catlab already uses Requires.jl for other graphics features, including [TikzPictures.jl](https://github.com/JuliaTeX/TikzPictures.jl) (which expects the user to have a full LaTeX installation!)
- As a consequence, users of Catlab would have to manually import Graphviz_jll to use it, but Catalyst or other packages have the freedom to adopt a different policy by making Graphviz_jll a required dependency and importing it inside their own package.

It's not perfect but I don't have any better ideas. What does everybody think about this?

**Comment by christopher-dG** [comment]
That seems fine to me. This is sort of unrelated, but does having a package in your `[extras]` actually do anything? I think the only place it's ever used is for test dependencies (and you have to have a `[targets]` section to use those).

**Comment by epatters** [comment]
Great! I don't actually know what `[extras]` actually does beside serving as documentation. (I'd like the Julia package manager to move toward taking extra or optional dependencies more seriously, but that's a separate issue.)

Have you checked that this works? It won't be exercised by the current CI tests. If so, we can merge and I will update the docs later to use `Graphviz_jll` on CI.

**Comment by christopher-dG** [comment]
I have, the loading stuff seems to be working fine (but perhaps it would be best if one of you guys ran a more realistic test).

**Comment by epatters** [comment]
I confirmed that the loading works on my local machine. Specifically, I can output SVGs and build all the docs using `Graphviz_jll`. So that's good!

However, I found another issue with `Graphviz_jll`, at least on my machine (a Mac). Whenever I run `dot`, I get the warning

```
Warning: Could not load "/Users/epatters/.julia/artifacts/6457d23222d6cb27ff900ad8d7ecaa0bfb2c4332/lib/graphviz/libgvplugin_pango.6.dylib" - It was found, so perhaps one of its dependents was not.  Try ldd.
```

I believe that Pango is used by Graphviz [only for PDF output](https://graphviz.org/faq/#FaqPDF). Indeed, the PDF output is broken on my system:

```bash
epatters$ echo 'digraph g { n1 -> n2; }' | /Users/epatters/.julia/artifacts/6457d23222d6cb27ff900ad8d7ecaa0bfb2c4332/bin/dot -Tpdf
Warning: Could not load "/Users/epatters/.julia/artifacts/6457d23222d6cb27ff900ad8d7ecaa0bfb2c4332/lib/graphviz/libgvplugin_pango.6.dylib" - It was found, so perhaps one of its dependents was not.  Try ldd.
Warning: Could not load "/Users/epatters/.julia/artifacts/6457d23222d6cb27ff900ad8d7ecaa0bfb2c4332/lib/graphviz/libgvplugin_pango.6.dylib" - It was found, so perhaps one of its dependents was not.  Try ldd.
Format: "pdf" not recognized. Use one of: canon cmap cmapx cmapx_np dot dot_json eps fig gv imap imap_np ismap json json0 mp pdf pic plain plain-ext png pov ps ps2 svg svgz tk vdx vml vmlz xdot xdot1.2 xdot1.4 xdot_json
```

A similar problem was reported for Graphviz in conda-forge (https://github.com/conda-forge/graphviz-feedstock/issues/18) and later fixed (https://github.com/conda-forge/graphviz-feedstock/pull/23).

*Summary*: I will merge this PR into Catlab, since it does not break anything on its own and seems to work correctly, but it seems that issues remain with `Graphviz_jll`.

**Comment by epatters** [comment]
Thanks again to everyone who made this happen! I will file an issue at Yggdrasil about the lingering problem.

**Pull request merged**
