### PR TITLE
DOC: add sketch for partitions

### PR DESCRIPTION
**Pull request by jpfairbanks**
@epatters could we embed quivers into our docs? I thought I could just put the iframe code in the markdown, but that didn't work.

### CODE REVIEW

**Comment by jpfairbanks** [comment]
I added the quiver style into this example once https://github.com/JuliaTeX/TikzCDs.jl/pull/4 is merged, we can remove that from this file.

**Comment by epatters** [comment]
Wait a second, I just realized that #493 was a pull request against this branch (I thought I was merging it into master). Was that intentional?

**Comment by jpfairbanks** [comment]
I was thinking of merging that into this PR and then merging this into master

**Comment by epatters** [comment]
OK, just making sure.

**Pull request merged**
